# Generated by Django 6.0.2 on 2026-03-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID_CARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('personal_number', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.id_card')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account+', to='accounts.user')),
            ],
        ),
    ]
